#!/bin/bash

set -e
set -u -o pipefail

SCRIPT_DIR="$(dirname "$0")"
case $# in
6)
    KEYCLOAK_IP="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    SERVICE_ACCOUNT_CLIENT_ID="$5"
    PERMISSION="$6"
    ;;
3)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_IP="$("${SCRIPT_DIR}"/getKeycloakIP)"
    REALM_NAME="$1"
    SERVICE_ACCOUNT_CLIENT_ID="$2"
    PERMISSION="$3"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <Service Account Client ID> <Permission>" >&2
    echo "   or: $(basename "$0") <Realm Name> <Service Account Client ID> <Permission>" >&2
    exit 1
    ;;
esac



ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

CLIENT="$("${SCRIPT_DIR}"/getClient "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "${SERVICE_ACCOUNT_CLIENT_ID}")"
CLIENT_ID="$(echo "${CLIENT}" | jq -r .[0].id)"

SERVICE_ACCOUNT_USER_ID="$(curl -k -sS -X GET "https://${KEYCLOAK_IP}/auth/admin/realms/${REALM_NAME}/clients/${CLIENT_ID}/service-account-user" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" | jq -r .id)"

PERMISSION_ACCESS_API="$(curl -k -sS -X GET "https://${KEYCLOAK_IP}/auth/admin/realms/${REALM_NAME}/roles/${PERMISSION}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" | jq -r .id)"

# Assign permission to client
curl -k -sS -X POST "https://${KEYCLOAK_IP}/auth/admin/realms/${REALM_NAME}/users/${SERVICE_ACCOUNT_USER_ID}/role-mappings/realm" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -d "[{\"id\":\"${PERMISSION_ACCESS_API}\",\"name\":\"${PERMISSION}\"}]"

"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_IP}" "${ADMIN_TOKEN}"
