#!/bin/bash

set -e
set -u -o pipefail

SCRIPT_DIR="$(dirname "$0")"

case $# in
6)
    KEYCLOAK_BASE_URL="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    SERVICE_ACCOUNT_CLIENT_ID="$5"
    CLIENT="$6"
    PERMISSION="$7"
    ;;
3)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_BASE_URL="$("${SCRIPT_DIR}"/getKeycloakBaseUrl)"
    REALM_NAME="$1"
    SERVICE_ACCOUNT_CLIENT_ID="$2"
    CLIENT_ID="$3"
    PERMISSION="$4"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <Service Account Client ID> <Client that provides the Permission> <Permission>" >&2
    echo "   or: $(basename "$0") <Realm Name> <Service Account Client ID> <Client that provides the Permission> <Permission>" >&2
    exit 1
    ;;
esac



ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_BASE_URL}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

SERVICE_ACCOUNT_CLIENT="$("${SCRIPT_DIR}"/getClient "${KEYCLOAK_BASE_URL}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "${SERVICE_ACCOUNT_CLIENT_ID}")"
ID_SERVICE_ACCOUNT_CLIENT="$(echo "${SERVICE_ACCOUNT_CLIENT}" | jq -r .[0].id)"

SERVICE_ACCOUNT_USER_ID="$(curl -k -sS -X GET "${KEYCLOAK_BASE_URL}/admin/realms/${REALM_NAME}/clients/${ID_SERVICE_ACCOUNT_CLIENT}/service-account-user" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" | jq -r .id)"

ROLE_OWNER_CLIENT="$("${SCRIPT_DIR}"/getClient "${KEYCLOAK_BASE_URL}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "${CLIENT_ID}" | jq -r .[0].id)"

PERMISSION_ACCESS_API="$(curl -k -sS -X GET "${KEYCLOAK_BASE_URL}/admin/realms/${REALM_NAME}/clients/${ROLE_OWNER_CLIENT}/roles" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}")"

PERMISSION_ID="$(echo "${PERMISSION_ACCESS_API}" | jq -r ".[] | select(.name==\"${PERMISSION}\")" | jq -r .id)"

# Assign permission to client
curl -k -sS -X POST "${KEYCLOAK_BASE_URL}/admin/realms/${REALM_NAME}/users/${SERVICE_ACCOUNT_USER_ID}/role-mappings/clients/${ROLE_OWNER_CLIENT}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -d "[{\"id\":\"${PERMISSION_ID}\",\"name\":\"${PERMISSION}\"}]"

"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_BASE_URL}" "${ADMIN_TOKEN}"
