#!/bin/bash

set -e
set -u -o pipefail

SCRIPT_DIR="$(dirname "$0")"

case $# in
7)
    KEYCLOAK_BASE_URL="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    CLIENT="$5"
    REALM_ROLE_NAME="$6"
    CLIENT_ROLE_NAME="$7"
    ;;
4)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_BASE_URL="$("${SCRIPT_DIR}"/getKeycloakBaseUrl)"
    REALM_NAME="$1"
    CLIENT="$2"
    REALM_ROLE_NAME="$3"
    CLIENT_ROLE_NAME="$4"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <Client Name> <Realm Role Name> <Client Role Name>" >&2
    echo "   or: $(basename "$0") <Realm Name> <Client Name> <Realm Role Name> <Client Role Name>" >&2
    exit 1
    ;;
esac

ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_BASE_URL}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

ID_OF_CLIENT=$("${SCRIPT_DIR}"/getClient "${REALM_NAME}" "${CLIENT}" | jq -r .[].id)


REALM_ROLE_ID=$(curl -k -sS -X GET "${KEYCLOAK_BASE_URL}/admin/realms/${REALM_NAME}/roles/${REALM_ROLE_NAME}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" | jq -r .id)


CLIENT_ROLE="$(curl -X GET "${KEYCLOAK_BASE_URL}/admin/realms/${REALM_NAME}/clients/$ID_OF_CLIENT/roles/${CLIENT_ROLE_NAME}" \
     -H "Content-Type: application/json" \
     -H "Authorization: bearer $ACCESS_TOKEN")"


curl -X POST "${KEYCLOAK_BASE_URL}/admin/realms/${REALM_NAME}/roles-by-id/${REALM_ROLE_ID}/composites" \
     -H "Content-Type: application/json" \
     -H "Authorization: bearer $ACCESS_TOKEN" \
     -d "[${CLIENT_ROLE}]"
