#!/bin/bash

set -e
set -u -o pipefail

case $# in
4)
    KEYCLOAK_IP="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_JSON_DATA="$4"
    ;;
1)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_IP="$("${SCRIPT_DIR}"/getKeycloakIP)"
    REALM_JSON_DATA="$1"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Json Data>" >&2
    echo "   or: $(basename "$0") <Realm Json Data>" >&2
    exit 1
    ;;
esac


ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

realmName="$(echo "${REALM_JSON_DATA}" | jq -r .realm)"
echo "<------- { Create Realm : ===> '$realmName' } ------->"
curl -k -sS -X POST "https://${KEYCLOAK_IP}/auth/admin/realms" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -d "${REALM_JSON_DATA}"

"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_IP}" "${ADMIN_TOKEN}"
