#!/bin/bash

set -e
set -u -o pipefail

set -e
set -u -o pipefail

SCRIPT_DIR="$(dirname "$0")"
case $# in
6)
    KEYCLOAK_IP="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    IDP_ALIAS="$5"
    ROLE_MAPPER_ID="$6"
    ;;
3)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_IP="$("${SCRIPT_DIR}"/getKeycloakIP)"
    REALM_NAME="$1"
    IDP_ALIAS="$2"
    ROLE_MAPPER_ID="$3"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <IDP alias> <Roler Mapper ID>" >&2
    echo "   or: $(basename "$0") <Realm Name> <IDP alias> <Roler Mapper ID>" >&2
    exit 1
    ;;
esac


ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

curl -k -sS -X DELETE "https://${KEYCLOAK_IP}/auth/admin/realms/${REALM_NAME}/identity-provider/instances/${IDP_ALIAS}/mappers/${ROLE_MAPPER_ID}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}"

"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_IP}" "${ADMIN_TOKEN}"
