#!/bin/bash

set -e
set -u -o pipefail

case $# in
6)
    KEYCLOAK_IP="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    CLIENT_NAME="$5"
    CLIENT_SCOPE_NAME="$6"
    ;;
3)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_IP="$("${SCRIPT_DIR}"/getKeycloakIP)"
    REALM_NAME="$1"
    CLIENT_NAME="$2"
    CLIENT_SCOPE_NAME="$3"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <CLient Name> <Client Scope Name>" >&2
    echo "   or: $(basename "$0") <Realm Name> <Client Name> <Client Scope Name>" >&2
    exit 1
    ;;
esac

ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"


CLIENT_ID="$("${SCRIPT_DIR}"/getClient "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "${CLIENT_NAME}" | jq -r .[0].id )"

DEFAULT_CLIENT_SCOPES="$("${SCRIPT_DIR}"/getClientDefaultClientScopes "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "${CLIENT_ID}")"
SCOPE_ID="$(echo "${DEFAULT_CLIENT_SCOPES}" | jq -r --arg CLIENT_SCOPE_NAME "$CLIENT_SCOPE_NAME" '.[] | select(.name==$CLIENT_SCOPE_NAME) | .id' )"
if [ "${SCOPE_ID}" == "" ]; then
        echo "The scope '${CLIENT_SCOPE_NAME}' is not of the list of scopes set as default client scope"
        exit 0
fi

BASE_CLIENT_DEFAULT_SCOPES_URL="https://${KEYCLOAK_IP}/auth/admin/realms/${REALM_NAME}/clients/${CLIENT_ID}/default-client-scopes"
curl -k -sS -X DELETE "${BASE_CLIENT_DEFAULT_SCOPES_URL}/${SCOPE_ID}" \
                        -H "Content-Type: application/json" \
                        -H "Authorization: Bearer ${ACCESS_TOKEN}"


"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_IP}" "${ADMIN_TOKEN}"
