#!/bin/bash

set -e
set -u -o pipefail
shopt -s inherit_errexit

SCRIPT_DIR="$(dirname "$0")"
case $# in
5)
    KEYCLOAK_IP="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    CLIENT_ID="$5"
    ;;
2)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_IP="$("${SCRIPT_DIR}"/getKeycloakIP)"
    REALM_NAME="$1"
    CLIENT_ID="$2"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <Client ID>" >&2
    echo "   or: $(basename "$0") <Realm Name> <Client ID>" >&2
    exit 1
    ;;
esac

ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

# Get Useful information first
client="$("${SCRIPT_DIR}"/getClient "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "${CLIENT_ID}")"
id_client="$(echo "${client}" | jq -r .[0].id)"

# Enabled permissions
curl -k -sS -X PUT "https://${KEYCLOAK_IP}/auth/admin/realms/${REALM_NAME}/clients/${id_client}/management/permissions" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -d '{"enabled":"true"}'

"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_IP}" "${ADMIN_TOKEN}"
