#!/bin/bash

set -e
set -u -o pipefail 

SCRIPT_DIR="$(dirname "$0")"


case $# in
2)
    KEYCLOAK_BASE_URL="$1"
    REALM_NAME="$2"
    ;;
1)
    KEYCLOAK_BASE_URL="$("${SCRIPT_DIR}"/getKeycloakBaseUrl)"
    REALM_NAME="$1"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Realm Name>" >&2
    echo "   or: $(basename "$0") <Realm Name>" >&2
    exit 1
    ;;
esac

CERTIFICATE="$(curl -k -sS $KEYCLOAK_BASE_URL/realms/$REALM_NAME/protocol/openid-connect/certs | jq -r .keys[0].x5c[0])"
cat <<EOF > x5c-cert-formated.pem
-----BEGIN CERTIFICATE-----
$CERTIFICATE
-----END CERTIFICATE-----
EOF
cat x5c-cert-formated.pem
rm x5c-cert-formated.pem
