#!/bin/bash

set -e
set -u -o pipefail

SCRIPT_DIR="$(dirname "$0")"
case $# in
5)
    KEYCLOAK_IP="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    IDP_ALIAS="$5"
    ;;
2)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_IP="$("${SCRIPT_DIR}"/getKeycloakIP)"
    REALM_NAME="$1"
    IDP_ALIAS="$2"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <IDP Alias>" >&2
    echo "   or: $(basename "$0") <Realm Name> <IDP Alias>" >&2
    exit 1
    ;;
esac

ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

REALM_MANAGEMENT_ID="$("${SCRIPT_DIR}"/getClient "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "realm-management" | jq -r .[0].id)"

IDP_PERMISSIONS="$("${SCRIPT_DIR}"/getIdentityProviderPermissions "${KEYCLOAK_IP}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}" "${REALM_NAME}" "${IDP_ALIAS}")"
SCOPE_PERMISSIONS_TOKEN_EXCHANGE_ID="$(echo "${IDP_PERMISSIONS}" | jq -r .scopePermissions.\"token-exchange\")"

curl -k -sS -X GET "https://${KEYCLOAK_IP}/auth/admin/realms/${REALM_NAME}/clients/${REALM_MANAGEMENT_ID}/authz/resource-server/permission/scope/${SCOPE_PERMISSIONS_TOKEN_EXCHANGE_ID}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}"

"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_IP}" "${ADMIN_TOKEN}"
