#!/bin/bash
set -e
set -u -o pipefail

SCRIPT_DIR="$(dirname "$0")"

case $# in
5)
    KEYCLOAK_BASE_URL="$1"
    ADMIN_USERNAME="$2"
    ADMIN_PASSWORD="$3"
    REALM_NAME="$4"
    USER_FEDERATION_NAME="$5"
    ;;
2)
    ADMIN_USERNAME="$("${SCRIPT_DIR}"/getAdminUsername)"
    ADMIN_PASSWORD="$("${SCRIPT_DIR}"/getAdminPassword)"
    KEYCLOAK_BASE_URL="$("${SCRIPT_DIR}"/getKeycloakBaseUrl)"
    REALM_NAME="$1"
    USER_FEDERATION_NAME="$2"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Admin User Name> <Admin Password> <Realm Name> <User Federation Name>" >&2
    echo "   or: $(basename "$0") <Realm Name> <User Federation Name>" >&2
    exit 1
    ;;
esac

ADMIN_TOKEN="$("${SCRIPT_DIR}"/getAdminToken "${KEYCLOAK_BASE_URL}" "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}")"
ACCESS_TOKEN="$(echo "${ADMIN_TOKEN}" | jq -r .access_token)"

curl -k -sS -X GET "${KEYCLOAK_BASE_URL}/admin/realms/${REALM_NAME}/components?type=org.keycloak.storage.UserStorageProvider&parent=${REALM_NAME}&name=${USER_FEDERATION_NAME}" \
    -H "Content-Type: application/json" \
    -H "Authorization: bearer ${ACCESS_TOKEN}"

"${SCRIPT_DIR}"/logoutAdminSession "${KEYCLOAK_BASE_URL}" "${ADMIN_TOKEN}"
