#!/bin/bash

set -e
set -u -o pipefail

SCRIPT_DIR="$(dirname "$0")"

case $# in
2)
    KEYCLOAK_BASE_URL="$1"
    TOKEN="$2"
    ;;
1)
    KEYCLOAK_BASE_URL="$("${SCRIPT_DIR}"/getKeycloakBaseUrl)"
    TOKEN="$1"
    ;;
*)
    echo "Wrong number of parameters" >&2
    echo "Usage: $(basename "$0") <Keycloak IP> <Token>" >&2
    echo "   or: $(basename "$0") <Token>" >&2
    exit 1
    ;;
esac

ACCESS_TOKEN="$(echo "${TOKEN}" | jq -r .access_token)"
SESSION_STATE="$(echo "${TOKEN}" | jq -r .session_state)"

curl -k -sS -X DELETE "${KEYCLOAK_BASE_URL}/admin/realms/master/sessions/${SESSION_STATE}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${ACCESS_TOKEN}"
